### ISSUE TITLE
Приложение, использующее WPFObjects падает если в нём используется read

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1572]
```
{$apptype windows}//<- Обязательно
uses GraphWPF, WPFObjects;

procedure OnClick(x, y: real; n: integer);
begin
  ReadLnString;
end;

begin
  GraphWPF.OnMouseDown:=OnClick;
end.
```

У аналогичного кода для ABCObjects:
```
{$apptype windows}
uses GraphABC, ABCObjects;

procedure OnClick(x, y: integer; n: integer);
begin
  ReadLnString;
end;

begin
  GraphABC.OnMouseDown:=OnClick;
end.
```
При нажатии на любую точку внутри окна происходит следующее исключение:
```
System.Threading.ThreadStateException: Thread is not running; it cannot be suspended.
   at PABCSystem.PABCSystem.Read(String& x) in C:\Program Files (x86)\PascalABC.NET\LibSource\PABCSystem.pas:line 4691
   at PABCSystem.PABCSystem.ReadString() in C:\Program Files (x86)\PascalABC.NET\LibSource\PABCSystem.pas:line 4937
   at PABCSystem.PABCSystem.ReadlnString() in C:\Program Files (x86)\PascalABC.NET\LibSource\PABCSystem.pas:line 4969
   at Program32.Program.OnClick(Int32 x, Int32 y, Int32 n) in C:\PABCWork.NET\Program32.pas:line 6
   at GraphABC.ABCControl.OnMouseDown(Object sender, MouseEventArgs e) in C:\Program Files (x86)\PascalABC.NET\LibSource\GraphABC.pas:line 2338
   at System.Windows.Forms.Control.OnMouseDown(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseDown(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by miks1965** [comment]
Не используйте их вместе.

Приложения GraphWPF устроены по-другому нежели GraphABC.

Кроме того, нельзя совместно использовать модули GraphWPF и WPFObjects, а также совсем невразумительно использовать {$apptype windows}

Это не планировалось, но у меня приложение
```
uses WPFObjects;

procedure OnClick(x, y: real; n: integer);
begin
  ReadLnString;
end;

begin
  OnMouseDown:=OnClick;
end.
```
работает. Оно работает странно, но без исключений.

Просим вас также не публиковать Issue по библиотекам - они будут закрываться. Их можно обсуждать на форуме.

**Comment by miks1965** [comment]
Без проблем. Поясните, в чём суть фикса. В Issue говорилось про GraphWPF, вы же исправляете GraphABC. Что то тут не так

**Comment by SunSerega** [comment]
Название про GraphWPF, но там было сравнение с GraphABC. И программа с GraphWPF работала примерно как ожидалось, а вылет GraphABC был неправильный.

Суть в том, что при чтении не из главного потока - блокировало всё равно главный. То есть если главный ещё не завершился - получали неопределённое поведение (обычно ReadlnString возвращало пустую строку а главный поток зависал, но бывало и по другому).

Я решил это тем - что вместо переменной хранящей главный поток я сделал очередь потоков, ожидающих ввода. Это не только работает с любым потоком, но если несколько потоков сразу вызвали Read - теперь они все будут работать (и в определённом порядке получать введённые данные).
