### ISSUE TITLE
Исключение в .exe, если в записи, которая читается из файла, отсутствует конструктор без аргументов, но есть другие конструкторы

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1600]
Код:
```
type
  T = record
    c: char;
    
    public constructor(a: char) := exit;
  end;

begin
  var f: file;
  rewrite(f,'a.dat');
  var a: T;
  f.Write(a);
  f.Close;
  reset(f,'a.dat');
  Read(f,a);//<- Здесь возникает ошибка
  f.Close;
end.
```
С типизированными файлами тоже самое

Если убрать конструктор с аргументом, то всё нормально.
Если объявить безаргументный конструктор `public constructor := exit;` тоже всё нормально.

**Comment by AIexandrKotov** [comment]
Само исключение:
```
Unhandled Exception: System.MissingMethodException: No parameterless constructor defined for this ob
ject.
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck,
 Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillC
ache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at PABCSystem_implementation______.PABCSystem_implementation______.AbstractBinaryFileReadT(Abstra
ctBinaryFile f, Type t, Int32& ind, Boolean in_arr) in C:\Program Files (x86)\PascalABC.NET\LibSourc
e\PABCSystem.pas:line 6361
   at PABCSystem.PABCSystem.BinaryFileRead(BinaryFile& f, Type ElementType) in C:\Program Files (x86
)\PascalABC.NET\LibSource\PABCSystem.pas:line 6625
   at Program52.Program.$Main() in C:\PABCWork.NET\Program52.pas:line 15
   at Program52.Program.Main()
```

**Comment by SunSerega** [comment]
PABCSystem.pas, строчки 6359-6367:
```
  else if t.IsValueType then
  begin
    elem := Activator.CreateInstance(t);
    fa := t.GetFields(System.Reflection.BindingFlags.GetField or System.Reflection.BindingFlags.Instance or System.Reflection.BindingFlags.Public or System.Reflection.BindingFlags.NonPublic);
    for var i := 0 to fa.Length - 1 do
      if {not fa[i].IsStatic and} not fa[i].IsLiteral then
        fa[i].SetValue(elem, AbstractBinaryFileReadT(f, fa[i].FieldType, ind, in_arr));
    Result := elem;
  end
```
Ошибка вылетает на `Activator.CreateInstance`.
Вот, нашёл на стак оверфлоу то, что работает и без конструктора:
```
type
  r1 = record
    
    x,y: integer;
    
    constructor(a: byte) := exit;
    
    public function ToString: string; override :=
    'экземпляр типа r1';
    
  end;

begin
  var t := typeof(r1);
  var o: object;
  o :=
    System.Linq.Expressions.Expression.Lambda&<Func0<object>>(
      System.Linq.Expressions.Expression.Convert(
        System.Linq.Expressions.Expression.Default(t),
        typeof(object)
      )
    ).Compile()();
  
  writeln(o);
end.
```
Попробую декомпилировать и вытащить часть которая отвечает за создание дефолтного экземпляра...
