### ISSUE TITLE
Замечания по Linux-сборке

### ISSUE THREAD

**Issue by Wohlstand** [pascalabcnet/pascalabcnet#1812]
У меня на борту Linux Mint 19.1 (под капотом Ubuntu 18.04)

Во первых, `xbuild` в скрипте теперь нужно заменить на `msbuild`
```
>>>> xbuild tool is deprecated and will be removed in future updates, use msbuild instead <<<<
```

Во вторых, оно не собирается:
```
Loading core...

Unhandled Exception:
System.TypeInitializationException: The type initializer for 'PascalABCCompiler.SystemLibrary.SystemLibrary' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x0008b] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st, SymbolTable.TreeConverterSymbolTable tcst) [0x00000] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary.initialize_types () [0x002df] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary.make_types () [0x00000] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary.initialize () [0x00000] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary..cctor () [0x00044] in <c02e13497c244eeea68e871c361e4be3>:0 
   --- End of inner exception stack trace ---
  at PascalABCCompiler.Compiler.Reload () [0x0000e] in <25f3a26d52f24aa89c9941d9dab840c5>:0 
  at (wrapper remoting-invoke-with-check) PascalABCCompiler.Compiler.Reload()
  at PascalABCCompiler.Compiler..ctor (PascalABCCompiler.SourceFilesProviderDelegate SourceFilesProvider, PascalABCCompiler.ChangeCompilerStateEventDelegate ChangeCompilerState) [0x000d9] in <25f3a26d52f24aa89c9941d9dab840c5>:0 
  at (wrapper remoting-invoke-with-check) PascalABCCompiler.Compiler..ctor(PascalABCCompiler.SourceFilesProviderDelegate,PascalABCCompiler.ChangeCompilerStateEventDelegate)
  at PascalABCCompiler.ConsoleCompiler.Reset () [0x0001b] in <e067146b96d7414c98c65764cea068df>:0 
  at PascalABCCompiler.ConsoleCompiler.Main (System.String[] initialArgs) [0x0009c] in <e067146b96d7414c98c65764cea068df>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'PascalABCCompiler.SystemLibrary.SystemLibrary' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x0008b] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node..ctor (System.Reflection.ConstructorInfo con_info) [0x0005f] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_constructor_node.get_compiled_constructor (System.Reflection.ConstructorInfo ci) [0x00013] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00058] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st) [0x00038] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type st, SymbolTable.TreeConverterSymbolTable tcst) [0x00000] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary.initialize_types () [0x002df] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary.make_types () [0x00000] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary.initialize () [0x00000] in <c02e13497c244eeea68e871c361e4be3>:0 
  at PascalABCCompiler.SystemLibrary.SystemLibrary..cctor () [0x00044] in <c02e13497c244eeea68e871c361e4be3>:0 
   --- End of inner exception stack trace ---
  at PascalABCCompiler.Compiler.Reload () [0x0000e] in <25f3a26d52f24aa89c9941d9dab840c5>:0 
  at (wrapper remoting-invoke-with-check) PascalABCCompiler.Compiler.Reload()
  at PascalABCCompiler.Compiler..ctor (PascalABCCompiler.SourceFilesProviderDelegate SourceFilesProvider, PascalABCCompiler.ChangeCompilerStateEventDelegate ChangeCompilerState) [0x000d9] in <25f3a26d52f24aa89c9941d9dab840c5>:0 
  at (wrapper remoting-invoke-with-check) PascalABCCompiler.Compiler..ctor(PascalABCCompiler.SourceFilesProviderDelegate,PascalABCCompiler.ChangeCompilerStateEventDelegate)
  at PascalABCCompiler.ConsoleCompiler.Reset () [0x0001b] in <e067146b96d7414c98c65764cea068df>:0 
  at PascalABCCompiler.ConsoleCompiler.Main (System.String[] initialArgs) [0x0009c] in <e067146b96d7414c98c65764cea068df>:0
```

Увидел старую задачу https://github.com/pascalabcnet/pascalabcnet/issues/1257 где произошло аналогичное, и я подтверждаю от себя, что оно не исправлено и всё ещё актуально.

Вкладываю [полный лог сборки](https://github.com/pascalabcnet/pascalabcnet/files/2923036/kkk.txt)

**Comment by Wohlstand** [comment]
**EDIT**: Даже нет, это ошибка не сборки, а как раз таки запуска:
```
vitaly@whl-pc-001l:~/_git_repos/pascalabcnet/bin$ chmod +x pabcnetc
vitaly@whl-pc-001l:~/_git_repos/pascalabcnet/bin$ ./pabcnetc
```

**Comment by Wohlstand** [comment]
Теперь нашёл то, что сборка валится из-за крэша:
```
mono /home/vitaly/_git_repos/pascalabcnet/bin/pabcnetcclear.exe "lab1_08.pas" (в каталоге: <xxxxxxx>/Alexa/lab1-08)
* Assertion at class-accessors.c:41, condition `mono_class_is_ginst (klass)' not met
Stacktrace:
  at <unknown> <0xffffffff>
  at (wrapper managed-to-native) System.RuntimeType.GetConstructors_native (System.RuntimeType,System.Reflection.BindingFlags) [0x00017] in <0f8aeac9d63d4b8aa575761bb4e65b79>:0
  at System.RuntimeType.GetConstructors_internal (System.Reflection.BindingFlags,System.RuntimeType) <0x0004e>
  at System.RuntimeType.GetConstructorCandidates (string,System.Reflection.BindingFlags,System.Reflection.CallingConventions,System.Type[],bool) <0x00124>
  at System.RuntimeType.GetConstructors (System.Reflection.BindingFlags) <0x00038>
  at System.Type.GetConstructors () <0x0000e>
  at PascalABCCompiler.TreeRealization.compiled_type_node.init_constructors () [0x00001] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.compiled_type_node.get_type_node (System.Type) [0x0004a] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.compiled_function_node..ctor (System.Reflection.MethodInfo) [0x000cb] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.compiled_function_node.get_compiled_method (System.Reflection.MethodInfo) [0x00019] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.NetHelper.NetHelper.FindName (System.Type,string) [0x00121] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.compiled_type_node.compiled_find (string) [0x00001] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.compiled_type_node.find (string,bool) [0x00032] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.compiled_type_node.find_in_type (string,SymbolTable.Scope,PascalABCCompiler.TreeRealization.type_node,bool) [0x00001] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.generic_instance_type_node.find_in_type (string,SymbolTable.Scope,PascalABCCompiler.TreeRealization.type_node,bool) [0x00003] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeRealization.common_type_node.find_in_type (string,SymbolTable.Scope,PascalABCCompiler.TreeRealization.type_node,bool) [0x0030a] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_method_call (PascalABCCompiler.SyntaxTree.method_call) [0x00597] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit (PascalABCCompiler.SyntaxTree.method_call) [0x00001] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.SyntaxTree.method_call.visit (PascalABCCompiler.SyntaxTree.IVisitor) [0x00001] in <85fafec25bce46f38556652cd24e77ee>:0
  at PascalABCCompiler.TreeConverter.returner.visit (PascalABCCompiler.SyntaxTree.expression) [0x00001] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong (PascalABCCompiler.SyntaxTree.expression) [0x0002e] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit (PascalABCCompiler.SyntaxTree.procedure_call) [0x00097] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.SyntaxTree.procedure_call.visit (PascalABCCompiler.SyntaxTree.IVisitor) [0x00001] in <85fafec25bce46f38556652cd24e77ee>:0
  at PascalABCCompiler.TreeConverter.returner.visit (PascalABCCompiler.SyntaxTree.statement) [0x00001] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong (PascalABCCompiler.SyntaxTree.statement) [0x00082] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit (PascalABCCompiler.SyntaxTree.statement_list) [0x000b4] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.SyntaxTree.statement_list.visit (PascalABCCompiler.SyntaxTree.IVisitor) [0x00001] in <85fafec25bce46f38556652cd24e77ee>:0
  at PascalABCCompiler.TreeConverter.returner.visit (PascalABCCompiler.SyntaxTree.statement) [0x00001] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong (PascalABCCompiler.SyntaxTree.statement) [0x00082] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code (PascalABCCompiler.SyntaxTree.statement_list) [0x0000d] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit (PascalABCCompiler.SyntaxTree.block) [0x00731] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.SyntaxTree.block.visit (PascalABCCompiler.SyntaxTree.IVisitor) [0x00001] in <85fafec25bce46f38556652cd24e77ee>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.hard_node_test_and_visit (PascalABCCompiler.SyntaxTree.syntax_tree_node) [0x00044] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit (PascalABCCompiler.SyntaxTree.procedure_definition) [0x0096e] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.SyntaxTree.procedure_definition.visit (PascalABCCompiler.SyntaxTree.IVisitor) [0x00001] in <85fafec25bce46f38556652cd24e77ee>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit (PascalABCCompiler.SyntaxTree.declarations) [0x00123] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.SyntaxTree.declarations.visit (PascalABCCompiler.SyntaxTree.IVisitor) [0x00001] in <85fafec25bce46f38556652cd24e77ee>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.weak_node_test_and_visit (PascalABCCompiler.SyntaxTree.syntax_tree_node) [0x00017] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit (PascalABCCompiler.SyntaxTree.implementation_node) [0x000ae] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.SyntaxTree.implementation_node.visit (PascalABCCompiler.SyntaxTree.IVisitor) [0x00001] in <85fafec25bce46f38556652cd24e77ee>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.hard_node_test_and_visit (PascalABCCompiler.SyntaxTree.syntax_tree_node) [0x00044] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_implementation (PascalABCCompiler.SyntaxTree.unit_module) [0x00139] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileImplementation (PascalABCCompiler.TreeRealization.common_unit_node,PascalABCCompiler.SyntaxTree.compilation_unit,PascalABCCompiler.TreeRealization.unit_node_list,System.Collections.Generic.List`1<PascalABCCompiler.Errors.Error>,System.Collections.Generic.List`1<PascalABCCompiler.Errors.CompilerWarning>,PascalABCCompiler.Errors.SyntaxError,System.Collections.Hashtable,PascalABCCompiler.TreeRealization.using_namespace_list,PascalABCCompiler.TreeRealization.using_namespace_list,System.Collections.Generic.Dictionary`2<PascalABCCompiler.SyntaxTree.syntax_tree_node, string>,bool,bool) [0x00164] in <9d4168bdd69949cfa4b3163084167132>:0
  at PascalABCCompiler.Compiler.CompileUnit (PascalABCCompiler.TreeRealization.unit_node_list,PascalABCCompiler.SyntaxTree.unit_or_namespace) [0x00b61] in <6c908e4b4ee24804aaa24039b7ee5809>:0
  at PascalABCCompiler.Compiler.CompileUnit (PascalABCCompiler.TreeRealization.unit_node_list,PascalABCCompiler.SyntaxTree.unit_or_namespace) [0x007c3] in <6c908e4b4ee24804aaa24039b7ee5809>:0
  at PascalABCCompiler.Compiler.Compile () [0x000cf] in <6c908e4b4ee24804aaa24039b7ee5809>:0
  at (wrapper remoting-invoke-with-check) PascalABCCompiler.Compiler.Compile () [0x00031] in <6c908e4b4ee24804aaa24039b7ee5809>:0
  at PascalABCCompiler.Compiler.Compile (PascalABCCompiler.CompilerOptions) [0x00009] in <6c908e4b4ee24804aaa24039b7ee5809>:0
  at (wrapper remoting-invoke-with-check) PascalABCCompiler.Compiler.Compile (PascalABCCompiler.CompilerOptions) [0x00032] in <6c908e4b4ee24804aaa24039b7ee5809>:0
  at PascalABCCompiler.ConsoleCompiler.Main (string[]) [0x000fe] in <74290fd0477a42058bd7f7cfb142a8a6>:0
  at (wrapper runtime-invoke) <Module>.runtime_invoke_int_object (object,intptr,intptr,intptr) [0x00054] in <74290fd0477a42058bd7f7cfb142a8a6>:0
/proc/self/maps:
411d4000-414cd000 rwxp 00000000 00:00 0
41ff9000-42009000 rwxp 00000000 00:00 0
56208e86d000-56208eca4000 r-xp 00000000 08:12 3545183                    /usr/bin/mono-sgen
56208eea3000-56208eeaa000 r--p 00436000 08:12 3545183                    /usr/bin/mono-sgen
56208eeaa000-56208eeaf000 rw-p 0043d000 08:12 3545183                    /usr/bin/mono-sgen
56208eeaf000-56208eec6000 rw-p 00000000 00:00 0
56208fb0f000-562093af3000 rw-p 00000000 00:00 0                          [heap]
7f39924d0000-7f3992550000 rw-p 00000000 00:00 0
7f3992554000-7f39925d4000 rw-p 00000000 00:00 0
7f39925d8000-7f3992658000 rw-p 00000000 00:00 0
7f399265c000-7f39926dc000 rw-p 00000000 00:00 0
7f39926e0000-7f3992760000 rw-p 00000000 00:00 0
7f3992764000-7f39927e4000 rw-p 00000000 00:00 0
7f39927e8000-7f3992868000 rw-p 00000000 00:00 0
7f399286c000-7f39928ec000 rw-p 00000000 00:00 0
7f39928f0000-7f3992970000 rw-p 00000000 00:00 0
7f3992974000-7f39929f4000 rw-p 00000000 00:00 0
7f39929f8000-7f3992a78000 rw-p 00000000 00:00 0
7f3992a7c000-7f3992afc000 rw-p 00000000 00:00 0
7f3992c58000-7f3992c5c000 rw-p 00000000 00:00 0
7f3992c60000-7f3992c64000 rw-p 00000000 00:00 0
7f3992c68000-7f3992ce8000 rw-p 00000000 00:00 0
7f3992cec000-7f3992d6c000 rw-p 00000000 00:00 0
7f3993170000-7f39931f0000 rw-p 00000000 00:00 0
7f39931f1000-7f39934f3000 r--p 00000000 08:12 3691334                    /usr/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll
Memory around native instruction pointer (0x7f399c112e97):
0x7f399c112e87  d2 4c 89 ce bf 02 00 00 00 b8 0e 00 00 00 0f 05  .L..............
0x7f399c112e97  48 8b 8c 24 08 01 00 00 64 48 33 0c 25 28 00 00  H..$....dH3.%(..
0x7f399c112ea7  00 44 89 c0 75 1f 48 81 c4 18 01 00 00 c3 0f 1f  .D..u.H.........
0x7f399c112eb7  00 48 8b 15 a9 bf 3a 00 f7 d8 41 b8 ff ff ff ff  .H....:...A.....
Native stacktrace:
	mono(+0xbfdb7) [0x56208e92cdb7]
	/lib/x86_64-linux-gnu/libpthread.so.0(+0x12890) [0x7f399c6ef890]
	/lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f399c112e97]
	/lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f399c114801]
	mono(+0x2f2bd8) [0x56208eb5fbd8]
	mono(+0x307c7b) [0x56208eb74c7b]
	mono(monoeg_assertion_message+0xa3) [0x56208eb75143]
	mono(+0x1baadd) [0x56208ea27add]
	mono(+0x1b55a9) [0x56208ea225a9]
	mono(+0x1d19da) [0x56208ea3e9da]
	[0x411d96df]
Debug info from gdb:
[New LWP 27050]
[New LWP 27051]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
DW_FORM_strp pointing outside of .debug_str section [in module /usr/lib/mono/aot-cache/amd64/mscorlib.dll.so]
0x00007f399c6ef23a in __waitpid (pid=27056, stat_loc=0x7ffcc672c86c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
30	../sysdeps/unix/sysv/linux/waitpid.c: Нет такого файла или каталога.
  Id   Target Id         Frame
* 1    Thread 0x7f399d29a780 (LWP 27049) "mono" 0x00007f399c6ef23a in __waitpid (pid=27056, stat_loc=0x7ffcc672c86c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
  2    Thread 0x7f399b7ff700 (LWP 27050) "SGen worker" 0x00007f399c6ea9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x56208eec3428) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
  3    Thread 0x7f399940f700 (LWP 27051) "Finalizer" 0x00007f399c6ed6d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x56208eeb45e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
Thread 3 (Thread 0x7f399940f700 (LWP 27051)):
#0  0x00007f399c6ed6d6 in futex_abstimed_wait_cancelable (private=0, abstime=0x0, expected=0, futex_word=0x56208eeb45e0) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  do_futex_wait (sem=sem@entry=0x56208eeb45e0, abstime=0x0) at sem_waitcommon.c:111
#2  0x00007f399c6ed7c8 in __new_sem_wait_slow (sem=0x56208eeb45e0, abstime=0x0) at sem_waitcommon.c:181
#3  0x000056208eaee2e7 in ?? ()
#4  0x000056208eaa727f in ?? ()
#5  0x00007f399c6e46db in start_thread (arg=0x7f399940f700) at pthread_create.c:463
#6  0x00007f399c1f588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Thread 2 (Thread 0x7f399b7ff700 (LWP 27050)):
#0  0x00007f399c6ea9f3 in futex_wait_cancelable (private=<optimized out>, expected=0, futex_word=0x56208eec3428) at ../sysdeps/unix/sysv/linux/futex-internal.h:88
#1  __pthread_cond_wait_common (abstime=0x0, mutex=0x56208eec3440, cond=0x56208eec3400) at pthread_cond_wait.c:502
#2  __pthread_cond_wait (cond=0x56208eec3400, mutex=0x56208eec3440) at pthread_cond_wait.c:655
#3  0x000056208eb5575a in ?? ()
#4  0x00007f399c6e46db in start_thread (arg=0x7f399b7ff700) at pthread_create.c:463
#5  0x00007f399c1f588f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
Thread 1 (Thread 0x7f399d29a780 (LWP 27049)):
#0  0x00007f399c6ef23a in __waitpid (pid=27056, stat_loc=0x7ffcc672c86c, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:30
#1  0x000056208e92ce61 in ?? ()
#2  <signal handler called>
#3  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#4  0x00007f399c114801 in __GI_abort () at abort.c:79
#5  0x000056208eb5fbd8 in ?? ()
#6  0x000056208eb74c7b in ?? ()
#7  0x000056208eb75143 in monoeg_assertion_message ()
#8  0x000056208ea27add in ?? ()
#9  0x000056208ea225a9 in ?? ()
#10 0x000056208ea3e9da in ?? ()
#11 0x00000000411d96df in ?? ()
#12 0x00007ffcc672dfe0 in ?? ()
#13 0x0000000000000014 in ?? ()
#14 0x0000000000000000 in ?? ()
=================================================================
Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries
used by your application.
=================================================================
Aborted (core dumped)
Сборка завершилась с ошибкой.
```

**Comment by Wohlstand** [comment]
Фикс есть в Mono 5.18, который вышед 5 дней назад, а у меня 5.16, как раз таки с этим злополучным багом... Попробую ка обновить сам mono...

**Comment by SunSerega** [comment]
> Попробую ка чуть позже...

А разве mono нельзя собрать самому, на любом билде, как любой другой проект?

**Comment by Wohlstand** [comment]
> А разве mono нельзя собрать самому, на любом билде, как любой другой проект?

Можно, это я и собираюсь сделать в ближайшее время, а хотя, сделал я тест, который упоминался в той задаче, и он у меня успешно отработал, на 5.18 и на 5.20

**Comment by Wohlstand** [comment]
Оставил комментарий разработчикам Mono, приложив мою сборку.

**Comment by miks1965** [comment]
Закрываю. У нас всё собиралось под Ubuntu
