### ISSUE TITLE
Внутренняя ошибка при использовании константы из другого пространства имён, равной nil.

### ISSUE THREAD

**Issue by AIexandrKotov** [pascalabcnet/pascalabcnet#1938]
unit1.pas:
```
unit unit1;

const C: object = nil;

end.
```
program.pas:
```
uses unit1;
 
type T = class end;
  
begin
  var a: T := c;
end.
```
Текст ошибки:
```
Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertSimpleConstant(IConstantDefinitionNode cnst, String name, ITypeNode type, IConstantNode constant_value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertNamespaceConstants(INamespaceConstantDefinitionNode[] Constants)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```
Архив: 
[test.zip](https://github.com/pascalabcnet/pascalabcnet/files/3178975/test.zip)

Если удалить готовый .pcu, то первая компиляция будет успешной.

**Comment by miks1965** [comment]
Это pcu
