### ISSUE TITLE
Компилятор падает, если елдить выражение с вложенной лямбдой, захватывающей переменную лямбды верхнего уровня

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2270]
```
type
  // обязательно в классе
  TemplateUtils = class
    
    static function f1(p: Action0) := p;
    
    static function ProcessCommand: sequence of Action0;
    begin
      
      // обязательно yield-ить выражение с лямбдой внутри
      yield f1(()->
      begin
        var s1 := '';
        
        var p: Action0 := ()->
        begin
          var s2 := s1;
        end;
        
      end);
      
    end;
    
  end;
  
begin end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.ArgumentException: Local passed in does not belong to this ILGenerator.
Parameter name: local
   at System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, LocalBuilder local)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ILocalBlockVariableReferenceNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.AssignToLocalVariableNode(IExpressionNode to, IExpressionNode from)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonMethodNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonTypeNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeImplementations(ICommonTypeNode[] types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by miks1965** [comment]
#2203 - это то же самое - не плодите
