### ISSUE TITLE
[PCUWriter] Компилятор падает если использовать метод описанный в другом модуле, через экземпляр класса из ещё 1 промежуточного модуля

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2307]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/5241564/0.zip)

```
unit u3;

uses u2;

procedure p1;
begin
  var a: t2;
  a.p0;
end;

end.
```
```
unit u2;

uses u1;

type
  t2 = class(t1) end;
  
end.
```
```
unit u1;

type
  t1 = class
    
    public procedure p0 := exit;
    
  end;
  
end.
```
При компиляции `u3` падает `PCUWriter`:
```
[0]Internal compiler error in module Compiler.Compile[u3.pas] :'System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PascalABCCompiler.PCU.PCUWriter.GetExtTypeReference(common_type_node ctn)
   at PascalABCCompiler.PCU.PCUWriter.GetMethodReference(common_method_node meth, Byte& is_def)
   at PascalABCCompiler.PCU.PCUWriter.WriteMethodReference(common_method_node meth)
   at PascalABCCompiler.PCU.PCUWriter.VisitCommonMethodCall(common_method_call expr)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatementList(statements_list stmt)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.SaveSemanticTree(CompilationUnit Unit, String TargetFileName, Boolean IncludeDebugInfo)
   at PascalABCCompiler.Compiler.SavePCU(CompilationUnit Unit) System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PascalABCCompiler.PCU.PCUWriter.GetExtTypeReference(common_type_node ctn)
   at PascalABCCompiler.PCU.PCUWriter.GetMethodReference(common_method_node meth, Byte& is_def)
   at PascalABCCompiler.PCU.PCUWriter.WriteMethodReference(common_method_node meth)
   at PascalABCCompiler.PCU.PCUWriter.VisitCommonMethodCall(common_method_call expr)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatementList(statements_list stmt)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.SaveSemanticTree(CompilationUnit Unit, String TargetFileName, Boolean IncludeDebugInfo)
   at PascalABCCompiler.Compiler.SavePCU(CompilationUnit Unit)'
```
И, пожалуйста, исправьте наконец тот факт что в IDE внутренние ошибки `PCUWriter`-а съедает.
Искать минимальный код таким багам очень больно когда не видно, произошла ошибка или нет, не заглядывая в папку.

**Comment by ibond84** [comment]
>И, пожалуйста, исправьте наконец тот факт что в IDE внутренние ошибки PCUWriter-а съедает.

Нет, не будем ничего менять. Ошибки сохранения pcu не такие критичные, чтобы блокировать работу. Это все равно что выбрасывать ошибку, если что-то где-то не закешировалось..
