### ISSUE TITLE
Компилятор падает, при передаче лямбды в процедурную переменную

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2328]
```
##

// Обязательно p0 - процедурная переменная, с методом или глобальной подпрограммой не воспроизводится
// Обязательно принимать в p хотя бы 1 параметр
var p0 := procedure(p: byte->()) -> exit();

// Обязательно вызвать передав лямбду
p0(b->exit());
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.TreeConverter.OpenMP.get_idents_from_dot_string(String s, SourceContext sc)
   at PascalABCCompiler.TreeConverter.OpenMP.ConvertToSyntaxType(type_node sem_type)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesTreeBuilder.visit(function_lambda_definition lambdaDefinition)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesTreeBuilder.visit(statement_list stmtList)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesTreeBuilder.BuildTree(statement_list statementList)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesSubstitutionsManager.Substitute(syntax_tree_visitor _visitor, declarations decls, statement_list _statementList)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.TreeConverter.OpenMP.get_idents_from_dot_string(String s, SourceContext sc)
   at PascalABCCompiler.TreeConverter.OpenMP.ConvertToSyntaxType(type_node sem_type)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesTreeBuilder.visit(function_lambda_definition lambdaDefinition)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesTreeBuilder.visit(statement_list stmtList)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesTreeBuilder.BuildTree(statement_list statementList)
   at TreeConverter.LambdaExpressions.Closure.CapturedVariablesSubstitutionsManager.Substitute(syntax_tree_visitor _visitor, declarations decls, statement_list _statementList)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/466180732
