### ISSUE TITLE
Три вложенных лямбды с захватами - падает

### ISSUE THREAD

**Issue by miks1965** [pascalabcnet/pascalabcnet#2365]
```
begin
  var b := Arr(false, true);
  b.SelectMany(x -> b.SelectMany(y -> b.Select(z -> y).Select(w -> x)));
end.
```

**Comment by miks1965** [comment]
NetGenerator.cs - 2272 - 
у {function <>lambda1(var z: boolean;): boolean} (она под индексом 1 в funcs) - function_code = null (восьмой вход в ConvertFunctionHeaders)

**Comment by miks1965** [comment]
y не находится, почему-то эта ошибка гасится. Тело думаю поэтому нулевое

**Comment by SunSerega** [comment]
Пожалуйста, вставляйте полный текст ошибки, это надо для поиска issue перед создания новых.
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionHeaders(ICommonNamespaceFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionHeaders(ICommonNamespaceFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by miks1965** [comment]
MaybeConvertFunctionLambdaDefinitionToProcedureLambdaDefinition(_function_lambda_definition);
этому виной. Если закомментировано - работает.
