### ISSUE TITLE
Компилятор падает, если 2 программы используют по 1 из 2 модулей, которые циклически связаны друг с другом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2387]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/5769652/0.zip)

`p1.pas`:
```
uses u1;

begin end.
```
`p2.pas`:
```
uses u2;

begin
  var o: t1;
end.
```

`u1.pas`:
```
unit u1;

interface

implementation

uses u2;

end.
````
`u2.pas`:
```
unit u2;

uses u1;

type
  t1 = class end;
  
end.
```
Если сначала откомпилировать `p1.pas`, а затем `p2.pas` - получаем ошибку:
```
[0]Internal compiler error in module Compiler.Compile[p2.pas] :'System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertLocalVariable(IVAriableDefinitionNode var, Boolean add_line_info, Int32 beg_line, Int32 end_line)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile() System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertLocalVariable(IVAriableDefinitionNode var, Boolean add_line_info, Int32 beg_line, Int32 end_line)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

Обратите внимание - `p2.pas` должно использовать что то из `u2.pas`. В данном коде это класс, но если использовать, к примеру, подпрограмму - тоже получаем ошибку, но совсем другую.
Когда будете составлять тесты - добавьте в `u2.pas` ещё несколько элементов и используйте их все в `p2.pas`.

**Comment by SunSerega** [comment]
Да и, в процессе поиска минимального кода я наткнулся на ещё 1 совсем другую, но возможно связанную ошибку:
```
[0]Internal compiler error in module Compiler.Compile[CombineQueues.pas] :'System.InvalidOperationException: Method '$Init$' does not have a method body.
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at PascalABCCompiler.NETGenerator.ILConverter.CloseTypes()
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile() System.InvalidOperationException: Method '$Init$' does not have a method body.
   at System.Reflection.Emit.TypeBuilder.CreateTypeNoLock()
   at System.Reflection.Emit.TypeBuilder.CreateType()
   at PascalABCCompiler.NETGenerator.ILConverter.CloseTypes()
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```
Она проявляется если в данном коде:
[0 - Copy.zip](https://github.com/pascalabcnet/pascalabcnet/files/5769684/0.-.Copy.zip)
Откомпилировать сначала `SpecPacker.pas`, а затем `CombineQueues.pas`.

Если эта ошибка не пропадёт после фикса данной issue - напишите, пожалуйста, чтоб я нашёл отдельный минимальный код и для неё.

**Comment by ibond84** [comment]
Первое не воспроизводится

**Comment by SunSerega** [comment]
Может мы что то по-разному делаем? Попробуйте точно вот так:

https://youtu.be/muRpyP7ENrk

Последний раз я собирал билд ровно 3 часа назад, поэтому дело явно не в версиях...

**Comment by SunSerega** [comment]
Да, ок, в этот раз я не подумал на `uses-in`, потому что `IL` генераторы я не трогал, но похоже дело таки в моих фиксах.
Добавлю исправление в существующий пулл.
