### ISSUE TITLE
PCUWriter падает, если неявно использовать operator implicit из неявно подключённого модуля

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2394]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/5787287/0.zip)
```
unit u1;

uses u2;

procedure p1;
begin
  // Обязательно неявно вызвать operator implicit
  p0(0);
end;

end.
```
```
unit u2;

uses u3;

procedure p0(o: t0) :=
u3.p0(o);

end.
```
```
unit u3;

type
  t0 = class
    static function operator implicit(i: integer): t0 := nil;
  end;
  
procedure p0(o: t0) := exit;

end.
```
При компиляции `u1.pas` получаем:
```
[0]Internal compiler error in module Compiler.Compile[u1.pas] :'System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PascalABCCompiler.PCU.PCUWriter.GetExtTypeReference(common_type_node ctn)
   at PascalABCCompiler.PCU.PCUWriter.GetMethodReference(common_method_node meth, Byte& is_def)
   at PascalABCCompiler.PCU.PCUWriter.WriteMethodReference(common_method_node meth)
   at PascalABCCompiler.PCU.PCUWriter.VisitCommonStaticMethodCall(common_static_method_call expr)
   at PascalABCCompiler.PCU.PCUWriter.VisitCommonNamespaceFunctionCall(common_namespace_function_call expr)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatementList(statements_list stmt)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.SaveSemanticTree(CompilationUnit Unit, String TargetFileName, Boolean IncludeDebugInfo)
   at PascalABCCompiler.Compiler.SavePCU(CompilationUnit Unit) System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PascalABCCompiler.PCU.PCUWriter.GetExtTypeReference(common_type_node ctn)
   at PascalABCCompiler.PCU.PCUWriter.GetMethodReference(common_method_node meth, Byte& is_def)
   at PascalABCCompiler.PCU.PCUWriter.WriteMethodReference(common_method_node meth)
   at PascalABCCompiler.PCU.PCUWriter.VisitCommonStaticMethodCall(common_static_method_call expr)
   at PascalABCCompiler.PCU.PCUWriter.VisitCommonNamespaceFunctionCall(common_namespace_function_call expr)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatementList(statements_list stmt)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.SaveSemanticTree(CompilationUnit Unit, String TargetFileName, Boolean IncludeDebugInfo)
   at PascalABCCompiler.Compiler.SavePCU(CompilationUnit Unit)'
```
Проблема, скорее всего, в слудующей функции в `Compiler\PCU\PCUWriter.cs`:
```
        private void AddIndirectUsedUnitsInStatement(statement_node stmt, Dictionary<common_namespace_node, bool> ns_dict, bool interf)
        {
            if (stmt == null)
                return;
            if (stmt is statements_list)
            {
                statements_list stmt_list = stmt as statements_list;
                foreach (local_block_variable lv in stmt_list.local_variables)
                {
                    AddIndirectUsedUnitsForType(lv.type, ns_dict, interf);
                }
                foreach (statement_node st in stmt_list.statements)
                    AddIndirectUsedUnitsInStatement(st, ns_dict, interf);
            }
            
        }
```
`u3` должно добавлять в список неявно подключённых к `u1` модулей. Но его не добавляет, потому что эта функция проверяет только локальные переменные. А надо смотреть ещё и на вызовы.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/868483137

**Comment by SunSerega** [comment]
А тест? И перед последним `if` не хватает `else`...
