### ISSUE TITLE
PCUWriter падает если шаблонный разорванный partial-класс наследует от другого шаблонного класса

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2432]
```
unit OpenCLABC;

interface

type
  t0<T> = class end;
  t1<T> = partial class(t0<T>)
    
  end;
  
implementation

type
  t1<T> = partial class(t0<T>)
    
  end;
  
end.
```
```
[0]Internal compiler error in module Compiler.Compile[u0.pas] :'System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at PascalABCCompiler.PCU.PCUWriter.WriteTypeReferenceWithDelay(common_type_node type)
   at PascalABCCompiler.PCU.PCUWriter.WriteGenericParameter(common_type_node type)
   at PascalABCCompiler.PCU.PCUWriter.WriteTypeReference(type_node type)
   at PascalABCCompiler.PCU.PCUWriter.WriteTypeList(List`1 types)
   at PascalABCCompiler.PCU.PCUWriter.WriteTypeReference(type_node type)
   at PascalABCCompiler.PCU.PCUWriter.VisitTypeMemberDefinition(common_type_node ctn)
   at PascalABCCompiler.PCU.PCUWriter.SaveSemanticTree(CompilationUnit Unit, String TargetFileName, Boolean IncludeDebugInfo)
   at PascalABCCompiler.Compiler.SavePCU(CompilationUnit Unit)
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/545206093
