### ISSUE TITLE
Компилятор падает на двух вложенных with, с последующим вызовом метода из внешнего with

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2467]
```
type
  node = class
    function f1: node := nil;
  end;
  
begin
  
  with new node do
  begin
    // Обязательно вложенный with
    with f1 do
    begin
    end;
    // Обязательно вызвать метод после вложенного with
    f1;
  end;
  
end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IThisNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonMethodCallNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IThisNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonMethodCallNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/716277790
