### ISSUE TITLE
PCUReader падает, если во Write() передать значение особого типа

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2511]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/7070966/0.zip)
```
## uses u;
Write(default(t1));
```
```
unit u;

type
  
  t0<T> = class
    // Обязательно operator= или operator<>
    static function operator=(a, b: t0<T>) := false;
  end;
  
  t1 = class
    // Обязательно operator implicit
    static function operator implicit<T>(a: t0<T>): t1 := nil;
  end;
  
end.
```
Сначала компилируете `u.pas`, затем `0.pas`.
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at PascalABCCompiler.PCU.PCUReader.GetAttributes()
   at PascalABCCompiler.PCU.PCUReader.GetParameter(common_function_node func)
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceInClassMember(Int32 offset, String name)
   at PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(SymbolInfo si, wrapped_definition_node wdn, String name)
   at PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(List`1 sil, String name, Int32 index)
   at SymbolTable.ClassScope.FindOnlyInType(String name, Scope CurrentScope)
   at PascalABCCompiler.PCU.wrapped_common_type_node.find_in_type(String name, Scope CurrentScope, type_node orig_generic_or_null, Boolean no_search_in_extension_methods)
   at PascalABCCompiler.PCU.wrapped_common_type_node.find_in_type(String name, Boolean no_search_in_extension_methods)
   at PascalABCCompiler.TreeRealization.common_type_node.get_implicit_conversion_to(type_node ctn)
   at PascalABCCompiler.TreeRealization.type_table.get_convertions(type_node from, type_node to, Boolean is_implicit)
   at PascalABCCompiler.TreeConverter.convertion_data_and_alghoritms.get_conversions(expressions_list factparams, parameter_list formalparams, Boolean is_alone_method_defined, location locg, Error& error)
   at PascalABCCompiler.TreeConverter.convertion_data_and_alghoritms.select_function(expressions_list parameters, List`1 functions, location loc, List`1 syntax_nodes_parameters, Boolean only_from_not_extensions)
   at PascalABCCompiler.TreeConverter.convertion_data_and_alghoritms.create_full_function_call(expressions_list exprs, List`1 si, location loc, common_type_node converted_type, common_function_node top_function, Boolean allow_procedure, List`1 syntax_nodes_parameters)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_method_call(method_call _method_call)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(method_call _method_call)
   at PascalABCCompiler.TreeConverter.returner.visit(expression expr)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(expression expr)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(procedure_call _procedure_call)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at PascalABCCompiler.PCU.PCUReader.GetAttributes()
   at PascalABCCompiler.PCU.PCUReader.GetParameter(common_function_node func)
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset)
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceInClassMember(Int32 offset, String name)
   at PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(SymbolInfo si, wrapped_definition_node wdn, String name)
   at PascalABCCompiler.TreeRealization.BasePCUReader.RestoreSymbols(List`1 sil, String name, Int32 index)
   at SymbolTable.ClassScope.FindOnlyInType(String name, Scope CurrentScope)
   at PascalABCCompiler.PCU.wrapped_common_type_node.find_in_type(String name, Scope CurrentScope, type_node orig_generic_or_null, Boolean no_search_in_extension_methods)
   at PascalABCCompiler.PCU.wrapped_common_type_node.find_in_type(String name, Boolean no_search_in_extension_methods)
   at PascalABCCompiler.TreeRealization.common_type_node.get_implicit_conversion_to(type_node ctn)
   at PascalABCCompiler.TreeRealization.type_table.get_convertions(type_node from, type_node to, Boolean is_implicit)
   at PascalABCCompiler.TreeConverter.convertion_data_and_alghoritms.get_conversions(expressions_list factparams, parameter_list formalparams, Boolean is_alone_method_defined, location locg, Error& error)
   at PascalABCCompiler.TreeConverter.convertion_data_and_alghoritms.select_function(expressions_list parameters, List`1 functions, location loc, List`1 syntax_nodes_parameters, Boolean only_from_not_extensions)
   at PascalABCCompiler.TreeConverter.convertion_data_and_alghoritms.create_full_function_call(expressions_list exprs, List`1 si, location loc, common_type_node converted_type, common_function_node top_function, Boolean allow_procedure, List`1 syntax_nodes_parameters)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_method_call(method_call _method_call)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(method_call _method_call)
   at PascalABCCompiler.TreeConverter.returner.visit(expression expr)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(expression expr)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(procedure_call _procedure_call)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by SunSerega** [comment]
В исходном коде у меня ещё 1 пересекающаяся внутренняя ошибка компилятора, которую я не могу отделить от этой.
Поэтому, пожалуйста, добавьте приоритета этой issue.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/1179126534
