### ISSUE TITLE
PCUReader падает, пытаясь прочитать 2 типа, если у них обоих есть по свойству

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2662]
```
## uses u;

// Обязательно использовать t2
new t2;
```
```
unit u;

type
  // Обязательно запись - с классом не воспроизводится
  t1 = record
    
    // Обязательно свойство
    property p1: byte read 0;
    
  end;
  
  t2 = class
    
    // Обязательно свойство, использующее t1
    property p2: word write
    begin
      var o: t1;
    end;
    
  end;
  
end.
```
Если компилировать основную программу после создания `u.pcu`:
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.KeyCollection.Enumerator.MoveNext()
   at PascalABCCompiler.PCU.PCUReader.RestoreWaitedMethodCodes()
   at PascalABCCompiler.Compiler.ClosePCUReadersAndWriters()
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by SunSerega** [comment]
Исправьте, пожалуйста, побыстрее, потому что я не представляю как к такому сделать временный обход...

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/2289120611

**Comment by SunSerega** [comment]
Вы добавили поле в начале, но потом его нигде не использовали...

**Comment by ibond84** [comment]
Ничего не понял. Какое поле? Я взял ровно ваш код

**Comment by SunSerega** [comment]
Я имею в виду изменения в компиляторе.

**Comment by ibond84** [comment]
Ну, будет использоваться. Для кешей инстанций в интеллисенсе
