### ISSUE TITLE
ILConverter падает, если использует загруженную из .pcu подпрограмму, которая создаёт и сразу упаковывает запись

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2663]
```
## uses u;

p1;
```
```
unit u;

type
  intr = interface
    procedure p;
  end;
  
  r = record(intr)
    // Обязательно использовать тот же конструктор, что и в p1
    procedure p := new r;
  end;
  
// Обязательно принимать интерфейс
procedure p0(o: intr) := exit;

// Обязательно передать экземпляр r, не присвоенный ни одной переменной
// (можно использовать как простой обход)
procedure p1 := p0(new r);

end.
```
Если компилировать основную программу после создания `u.pcu`:
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonConstructorCall value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonMethodNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICommonTypeNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeImplementations(ICommonTypeNode[] types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/2289247805
