### ISSUE TITLE
Компилятор падает, пытаясь сгенерировать IL подпрограммы с анонимным делегатом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2678]
```
type
  t1<T> = class
    
    // Обязательно функция
    function f1(b: byte) := default(T);
    
  end;
  
procedure p1<T>;
begin
  // Обязательно <T> из заголовка подпрограммы (не из описавшего её класса!)
  var a: t1<T>;
  // Обязательно авто-определение типа делегата f
  var f := a.f1;
end;

begin end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertMethodHeader(ICommonMethodNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeader(ICommonTypeNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaderAndRemoveFromList(ICommonTypeNode type, List`1 types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaders(ICommonTypeNode[] types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertMethodHeader(ICommonMethodNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeader(ICommonTypeNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaderAndRemoveFromList(ICommonTypeNode type, List`1 types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaders(ICommonTypeNode[] types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
Теперь выдается ошибка "Нельзя вывести тип анонимного делегата с генерик-параметрами. Укажите тип переменной явно."

https://github.com/pascalabcnet/pascalabcnet/actions/runs/2760113945
