### ISSUE TITLE
`(a??b).m` падает, если `a` - функция

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2694]
```
## function s := default(string);
(s??'').PadRight(10);
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IDoubleQuestionColonExpressionNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICompiledMethodCallNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```
Если поставить скобки вызову `s()` - ошибка пропадает.

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/2987582913
