### ISSUE TITLE
`ILConverter` падает на `foreach` по массиву шаблонных типов

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2783]
```
type
  // Обязательно пользовательский шаблонный тип
  t1<T> = class end;
  
begin
  // Обязательно массив
  // foreach по "a.AsEnumerable" не падает
  var a: array of t1<byte>;
  foreach var x in a do
end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NotSupportedException: Specified method is not supported.
   at System.Reflection.Emit.TypeBuilderInstantiation.GetMethodImpl(String name, BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers)
   at System.Type.GetMethod(String name)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IForeachNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertStatement(IStatementNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IStatementsListNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertBody(IStatementNode body)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/3979080814
