### ISSUE TITLE
`PCUWriter` падает, когда встречает вызов `extensionmethod`'а из неявно подключённого модуля

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2868]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/11567445/0.zip)
```
unit u1;

uses u2;

begin
  // Вызов extensionmethod'а из неявно подключённого u3
  ''.p1;
end.
```
```
unit u2;

uses u3;

end.
```
```
unit u3;

procedure p1(self: string); extensionmethod := exit;

end.
```
```
Internal compiler error in module Compiler.Compile[u1.pas] :'System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at PascalABCCompiler.PCU.PCUWriter.GetFunctionReference(common_namespace_function_node fn, Byte& is_def)
   at PascalABCCompiler.PCU.PCUWriter.WriteFunctionReference(common_namespace_function_node fn)
   at PascalABCCompiler.PCU.PCUWriter.VisitCommonNamespaceFunctionCall(common_namespace_function_call expr)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatementList(statements_list stmt)
   at PascalABCCompiler.PCU.PCUWriter.VisitStatement(statement_node sn)
   at PascalABCCompiler.PCU.PCUWriter.SaveSemanticTree(CompilationUnit Unit, String TargetFileName, Boolean IncludeDebugInfo)
   at PascalABCCompiler.Compiler.SavePCU(CompilationUnit Unit)
```

**Comment by ibond84** [comment]
Ресурсы там зачем?

**Comment by ibond84** [comment]
0.pas и u.pas там видимо лишние
