### ISSUE TITLE
`ILConverter` падает, если добавить атрибут к результату функции

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2880]
```
type
  [System.AttributeUsage(System.AttributeTargets.ReturnValue)]
  TestAttribute = sealed class(System.Attribute)
    
  end;
  
//TODO #2036
function f0 := 0;

[Result: Test]
// И так то же самое
//[return: Out]
function f1 := 0;

begin end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at PascalABCCompiler.NETGenerator.ILConverter.MakeAttribute(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionBody(ICommonFunctionNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionsBodies(ICommonFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
Reflection.Emit походу не поддерживает атрибуты для возвращаемых значений. Только MarshalAs через SetMarshal. Да и то функция устаревшая, но альтернатив мелкософт не приводит. А зачем вам вообще понадобились атрибуты для возвращаемого значения??

**Comment by SunSerega** [comment]
Мне - пока не понадобились. Тут всё проще, вижу краш компилятора - создаю issue.
Но если уж на то пошло, `[MarshalAs]` на результате таки может понадобится.
