### ISSUE TITLE
Компилятор падает, если в пользовательский метод `Equals` передать лямбду

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2892]
```
type
  // Обязательно внутри класса
  t1 = class
    
    // Не важно, статический ли метод
    //
    // Обязательно имя Equals
    //
    // Обязательно первый параметр - класс
    // (из .dll или паскалевский - не важно)
    //
    // Обязательно p должен принимать параметр,
    // чтобы лямбда ниже его авто-вычисляла
    public static function Equals(o: Exception; p: byte->()) := true;
    
  end;
  
begin
  // Обязательно передать именно лямбду,
  // а не существующую подпрограмму
  t1.Equals(nil, l->begin end);
end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.GetParamTypes(ICommonMethodNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertMethodHeader(ICommonMethodNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeader(ICommonTypeNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaderAndRemoveFromList(ICommonTypeNode type, List`1 types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaders(ICommonTypeNode[] types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
Не выводится lambda_any_type в Invoke. Кошмар.
