### ISSUE TITLE
Компилятор падает, если модуль имеет `$resource` с не существующим файлом

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2897]
[0.zip](https://github.com/pascalabcnet/pascalabcnet/files/11908051/0.zip)

При первой компиляции выдаёт ожидаемую ошибку:
```
Compiling assembly 0.pas...
[0][3,3] u.pas: Resource file 'non_existing_file' not found
```
Что не ожидаемо - так это то, что тут создаётся .pcu файл. Но это вторичная проблема. Проблема данной issue будет воспроизводится и без того.

На 2 и следующих компиляциях (когда .pcu уже сущесвует) компилятор падает:
```
Compiling assembly 0.pas...
[0]Internal compiler error in module Compiler.Compile[0.pas] :'System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.ResourceFileNotFound..ctor(String ResFileName, location sl)
   at PascalABCCompiler.Compiler.Compile() System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.ResourceFileNotFound..ctor(String ResFileName, location sl)
   at PascalABCCompiler.Compiler.Compile()'
```
Этот конструктор:
```
        public ResourceFileNotFound(string ResFileName, TreeRealization.location sl)
            : base(string.Format(StringResources.Get("COMPILATIONERROR_RESOURCEFILE_{0}_NOT_FOUND"), ResFileName), sl.doc.file_name)
        {
            this.sourceLocation = new SourceLocation(sl.doc.file_name, sl.begin_line_num, sl.begin_column_num, sl.end_line_num,sl.end_column_num);
        }
```
Тут в 2 местах используется `sl.doc`. Но после загрузки из .pcu оно null.

**Comment by SunSerega** [comment]
Аналогичная проблема с остальными директивами, которые могут быть загружены из .pcu . Только у большинство она проявится если сделать эти директивы невалидными после создания .pcu (к примеру удалить файл, на который директива ссылалась)

**Comment by ibond84** [comment]
https://github.com/pascalabcnet/pascalabcnet/actions/runs/5435780183
