### ISSUE TITLE
Начиная с офиц. билда 3.9.0.3383 компилятор падает под WinXP

### ISSUE THREAD

**Issue by spectatorBH** [pascalabcnet/pascalabcnet#2977]
Проблема в моей клонированной репе проявилась где-то 19.11.2023. Скорее всего, это либо из-за исправления #2955, либо #2957.

```
## //вылет компилятора в WinXP Pro SP3 (32-bit) даже при пустой программе
```
<details><summary>System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.</summary>
<p>

Внутренняя ошибка компилятора в модуле [pabcnetc.exe] : 
System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.PCU.PCUReader.FindTypeByHandle(Int32 off)
   at PascalABCCompiler.PCU.PCUReader.ReadNetExtType()
   at PascalABCCompiler.PCU.PCUReader.GetTypeReference()
   at PascalABCCompiler.PCU.PCUReader.ReadImplementingInterfaces()
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceCommonType(String name, Int32 offset)
   at PascalABCCompiler.PCU.PCUReader.GetCommonType(Int32 offset)
   at PascalABCCompiler.PCU.PCUReader.GetTypeReference()
   at PascalABCCompiler.PCU.PCUReader.CreateExpression(semantic_node_type snt)
   at PascalABCCompiler.PCU.PCUReader.CreateCompiledStaticMethodCall()
   at PascalABCCompiler.PCU.PCUReader.CreateExpression(semantic_node_type snt)
   at PascalABCCompiler.PCU.PCUReader.CreateBasicFunctionCall()
   at PascalABCCompiler.PCU.PCUReader.CreateExpression(semantic_node_type snt)
   at PascalABCCompiler.PCU.PCUReader.CreateBasicFunctionCall()
   at PascalABCCompiler.PCU.PCUReader.CreateExpression(semantic_node_type snt)
   at PascalABCCompiler.PCU.PCUReader.CreateIf()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateIf()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateIf()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateIf()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateIf()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateIf()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateIf()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   at PascalABCCompiler.PCU.wrapped_function_body.restore()
   at PascalABCCompiler.TreeRealization.common_namespace_function_call..ctor(common_namespace_function_node namespace_func, location loc)
   at PascalABCCompiler.PCU.PCUReader.CreateCommonNamespaceFunctionCall()
   at PascalABCCompiler.PCU.PCUReader.CreateExpression(semantic_node_type snt)
   at PascalABCCompiler.PCU.PCUReader.CreateCompiledStaticMethodCall()
   at PascalABCCompiler.PCU.PCUReader.CreateExpression(semantic_node_type snt)
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset, Boolean not_restore_code)
   at PascalABCCompiler.PCU.PCUReader.GetClassMethod(Int32 offset, Boolean not_restore_code)
   at PascalABCCompiler.PCU.PCUReader.GetMethodByOffset(Int32 offset)
   at PascalABCCompiler.PCU.PCUReader.GetMethodByOffset()
   at PascalABCCompiler.PCU.PCUReader.CreateMethodCall()
   at PascalABCCompiler.PCU.PCUReader.CreateExpression(semantic_node_type snt)
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.CreateStatementList()
   at PascalABCCompiler.PCU.PCUReader.CreateStatement()
   at PascalABCCompiler.PCU.PCUReader.GetCode(Int32 offset)
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceMethod(String name, Int32 offset, Boolean not_restore_code)
   at PascalABCCompiler.PCU.PCUReader.CreateInterfaceInClassMember(Int32 offset, String name)
   at PascalABCCompiler.PCU.WrappedClassScope.RestoreMembers(String name)
   at PascalABCCompiler.PCU.PCUReader.RestoreAllFields(common_type_node ctn)
   at PascalABCCompiler.PCU.PCUReader.ProcessWaitedToRestoreFields()
   at PascalABCCompiler.Compiler.ClosePCUReadersAndWriters()
   at PascalABCCompiler.Compiler.Compile()
</p>
</details> 

```
## '123'[1:2].Println; //а так уже другой трейсинг ошибки:
```

<details><summary>System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.</summary>
<p>

Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :
   System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   at PascalABCCompiler.SyntaxTree.statement_list.visit(IVisitor visitor)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   at PascalABCCompiler.SyntaxTree.block.visit(IVisitor visitor)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.hard_node_test_and_visit(syntax_tree_node tn)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   at PascalABCCompiler.SyntaxTree.program_module.visit(IVisitor visitor)
   at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging, Boolean for_intellisense, List`1 CompiledVariables)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(statement_list _statement_list)
   at PascalABCCompiler.SyntaxTree.statement_list.visit(IVisitor visitor)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.convert_strong(statement st)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit_program_code(statement_list program_code)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(block _block)
   at PascalABCCompiler.SyntaxTree.block.visit(IVisitor visitor)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.hard_node_test_and_visit(syntax_tree_node tn)
   at PascalABCCompiler.TreeConverter.syntax_tree_visitor.visit(program_module _program_module)
   at PascalABCCompiler.SyntaxTree.program_module.visit(IVisitor visitor)
   at PascalABCCompiler.TreeConverter.SyntaxTreeToSemanticTreeConverter.CompileInterface(compilation_unit SyntaxUnit, unit_node_list UsedUnits, List`1 ErrorsList, List`1 WarningsList, SyntaxError parser_error, Hashtable bad_nodes, using_namespace_list namespaces, Dictionary`2 docs, Boolean debug, Boolean debugging, Boolean for_intellisense, List`1 CompiledVariables)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list Units, Dictionary`2 DirectCompilationUnits, unit_or_namespace SyntaxUsesUnit, String prev_path)
   at PascalABCCompiler.Compiler.Compile()'
</p>
</details>

**Comment by ibond84** [comment]
Откомпилируйте PABCSystem на WindowsXP. Какого-то типа нет в старом .NET 4.0

**Comment by ibond84** [comment]
И напишите здесь сообщение об ошибке

**Comment by ibond84** [comment]
Судя пио обилию if-ов это StructuredObjectToString, а именно pp[i].GetValue(o)
В .NET 4.0 не было еще такой перегрузки

**Comment by spectatorBH** [comment]
Заменил PABCSystem.pas в последнем рабочем билде для XP на версию из более свежего проблемного билда и попытался её перекомпилировать.

1) Ругается на интерфейс `IReadOnlyCollection` в объявлении типов `IntRange` и `CharRange`: 
> PABCSystem.pas(622) : Неизвестное имя 'IReadOnlyCollection'
> PABCSystem.pas(694) : Неизвестное имя 'IReadOnlyCollection'
```pascal
IntRange = record(ICollection<integer>, IReadOnlyCollection<integer>, IEquatable<IntRange>)
...
CharRange = record(ICollection<char>, IReadOnlyCollection<char>, IEquatable<CharRange>)
```

2) Без `IReadOnlyCollection` ругается уже на отсутствие метода `ToHashSet` у типов `array of integer` и `array of string`: 
> PABCSystem.pas(5191) : ToHashSet не объявлен в типе array of integer
> PABCSystem.pas(5193) : ToHashSet не объявлен в типе array of string
```pascal
function HSetInt(params a: array of integer): HashSet<integer> := a.ToHashSet;
...
function HSetStr(params a: array of string): HashSet<string> := a.ToHashSet;
```

3) Ну и далее на отсутствие метода `ToHashSet` у типов `IntRange` и `CharRange`: 
> PABCSystem.pas(5199) : ToHashSet не объявлен в типе IntRange
>PABCSystem.pas(5201) : ToHashSet не объявлен в типе CharRange

```pascal
function HSet(a: IntRange): HashSet<integer> := a.ToHashSet;
...
function HSet(a: CharRange): HashSet<char> := a.ToHashSet;
```

**Comment by ibond84** [comment]
Выкинуть нафиг этот IReadOnlyCollection

**Comment by SunSerega** [comment]
> на отсутствие метода `ToHashSet`

Это, наверное, если вы убрали `ICollection` вместе с `IReadOnlyCollection`?

> Выкинуть нафиг этот IReadOnlyCollection

В не_древних версиях .Net он полезен. Может `{$ifdef}` ему какой то?

**Comment by spectatorBH** [comment]
> Это, наверное, если вы убрали ICollection вместе с IReadOnlyCollection?

Да нет, убирал только IReadOnlyCollection.

**Comment by SunSerega** [comment]
А, понятно. Его как метода тоже нет в той версии - надо конструктор вызывать вместо этого...
https://learn.microsoft.com/ru-ru/dotnet/api/system.linq.enumerable.tohashset?view=netframework-4.8.1

**Comment by samuraiGH** [comment]
>@SunSerega Может {$ifdef} ему какой то?
тогда будет собираться под xp. но если собрать под десяткой, а запустить под xp -- упадёт в рантайме

**Comment by samuraiGH** [comment]
Пожалуй, единственное, что можно сделать, это использовать разные `PABCSystem`. Когда программа собирается для 4.0 -- один вариант, когда 4.7 -- другой, ну и так далее...

Проще всё-таки `PABCSystem` ограничить типами, доступными в 4.0

**Comment by SunSerega** [comment]
> тогда будет собираться под xp. но если собрать под десяткой, а запустить под xp -- упадёт в рантайме

Мне почему то кажется что модуль перекомпилирует со специальными перед тем как собирать установщик для XP. Но теперь припоминается что вроде разработчики мне уже говорили что это не так...
Но `RebuildStandartModules.pas` таки компилируется несколько раз. Для чего это если не для разных установщиков?

> использовать разные `PABCSystem`

Это то же самое что использовать один `PABCSystem` с `ifdef` и компилировать с разными флагами, о чём я и говорю.

**Comment by samuraiGH** [comment]
>Мне почему то кажется что все модули специально перекомпилирует перед тем как собирать установщик для XP

А ну да, у нас же ещё и отдельный установщик для XP. Тогда пожалуй можно что-то сделать, да. Но это всё же плохая практика для стандартной библиотеки. Версий много и под каждую таким образом подстраиваться не лучшая идея

**Comment by SunSerega** [comment]
> Но это всё же плохая практика для стандартной библиотеки

Да, если бы это была значительная часть кода.

В данном случае в `$ifdef` надо засунуть только имя интерфейса в списке реализации.
Реализуемые методы можно оставить - они никому не мешают.
В итоге единственная разница это то, что на платформе, не имеющей `IReadOnlyCollection<T>` - `IntRange` нельзя будет присвоить переменной типа `IReadOnlyCollection<T>`.

**Comment by SunSerega** [comment]
Интересно что одно из изменений, которое тут ломает всё - было сделано ещё в начале года:
https://github.com/pascalabcnet/pascalabcnet/commit/a6d507d2bc75f5c3a89581cff0d244779c068d03#diff-7fa4c8a784dc9869a18055114f3eb8c2dcb49845334b2700c699286aadb30295R5219-R5221
@spectatorBH вы уверены что это недавно сломалось? Хотелось бы всё же разобраться...

**Comment by SunSerega** [comment]
@spectatorBH, ещё, когда пройдёт этот тест:
https://github.com/SunSerega/pascalabcnet/actions/runs/7154081042
Попробуйте взять установщик отсюда и протестить на нём:
https://github.com/SunSerega/pascalabcnet/releases/tag/unstable
(его пересоздаст если тест пройдёт успешно - желательно проверьте дату и имя коммита на гитхабе)

**Comment by spectatorBH** [comment]
Все ОК -- исправленная версия работает, по крайней мере PABCSystem теперь перекомпилируется на XP! 

Проблема с `.ToHashSet` в некоторых типах под .NET 4.0, видимо, была уже давно, но я её раньше просто не замечал, т.к. не пользовался теми функциями и не гонял никаких стресс-тестов, а в дистрибутив для XP всегда попадает один и тот же PABCSystem.pcu, скомпилированный под более новой средой. Хотя там в проектах, вроде, всегда был жестко указан `net4.0` как Target Platform. Странно, что это не помогает ловить такие баги с несовместимыми типами прямо на этапе сборки. И жалко, что в GitHub Actions нет встроенного runner'а на WinXP для CI.

**Comment by SunSerega** [comment]
> Странно, что это не помогает ловить такие баги с несовместимыми типами прямо на этапе сборки. И жалко, что в GitHub Actions нет встроенного runner'а на WinXP для CI

Да...
