### ISSUE TITLE
Компилятор падает, если попытаться вызвать пользовательский метод `Invoke` в наследнике класса `Form`

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#2997]
```
{$reference System.Windows.Forms.dll}
uses System.Windows.Forms;

type
  MyForm = sealed class(Form)
    
    static procedure Invoke(p: byte->()) := exit;
    
    static procedure p1 := Invoke(b->begin end);
    
  end;
  
begin end.
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.GetParamTypes(ICommonMethodNode func)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertMethodHeader(ICommonMethodNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeader(ICommonTypeNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaderAndRemoveFromList(ICommonTypeNode type, List`1 types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertTypeMemberHeaders(ICommonTypeNode[] types)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by ibond84** [comment]
Не воспроизводится

**Comment by SunSerega** [comment]
![image](https://github.com/pascalabcnet/pascalabcnet/assets/27270190/5e424000-0407-49d3-813f-7c3c0623541b)

**Comment by SunSerega** [comment]
Это было в моём кастомном билде, включающем последний коммит.
Но теперь я ещё скачал последнюю официального версию с сайта и на ней тоже воспроизводится.

**Comment by ibond84** [comment]
В мастере все работает.

**Comment by ibond84** [comment]
А, это если не запускать компилятор в отдельном процессе
