### ISSUE TITLE
Компилятор падает из за `external ''`

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#3023]
```
##
procedure p1;
  external '';
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.ArgumentException: Empty name is not legal.
Parameter name: dllName
   at System.Reflection.Emit.TypeBuilder.DefinePInvokeMethodHelperNoLock(String name, String dllName, String importName, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type[][] parameterTypeRequiredCustomModifiers, Type[][] parameterTypeOptionalCustomModifiers, CallingConvention nativeCallConv, CharSet nativeCharSet)
   at System.Reflection.Emit.TypeBuilder.DefinePInvokeMethodHelper(String name, String dllName, String importName, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] returnTypeRequiredCustomModifiers, Type[] returnTypeOptionalCustomModifiers, Type[] parameterTypes, Type[][] parameterTypeRequiredCustomModifiers, Type[][] parameterTypeOptionalCustomModifiers, CallingConvention nativeCallConv, CharSet nativeCharSet)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFunctionHeaders(ICommonNamespaceFunctionNode[] funcs)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by SunSerega** [comment]
А этот код не заденет?
```
## uses System.Runtime.InteropServices;

[DllImport('0.dll')]
procedure p1; external;
```
Сейчас он компилируется.

**Comment by ibond84** [comment]
Нет, там другая ветка срабатывает

```
if (_external_directive.modulename == null)
            {
            	if (!has_dll_import_attribute(context.top_function))
            	{
                    AddError(context.top_function.loc, "FUNCTION_MUST_HAVE_DLLIMPORT_ATTRIBUTE");
            	}
            	else
            	{
            		location loc2 = get_location(_external_directive);
            		pinvoke_statement pinv_stmt = new pinvoke_statement(loc2);
            		//statement_node_list sal = new statement_node_list(loc);
            		//sal.AddElement(ext_stmt);
            		statements_list sl2 = new statements_list(loc2);
            		sl2.statements.AddElement(pinv_stmt);
            		//return_value(sl);
            		context.code = sl2;
            		return;
            	}
            }
```

**Comment by iahung3** [comment]
Please make a new release.

**Comment by SunSerega** [comment]
Or at my fork - I have a branch that overrides the latest release every midnight (UTC): https://github.com/SunSerega/pascalabcnet/releases/tag/nightly-release-tag

**Comment by iahung3** [comment]
Thank you all.
