### ISSUE TITLE
Компилятор падает, если попытаться вызвать оператор

### ISSUE THREAD

**Issue by SunSerega** [pascalabcnet/pascalabcnet#3045]
```
## operator*();
```
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at SyntaxVisitors.ABCStatisticsVisitor.visit(procedure_call pc)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.DefaultVisit(syntax_tree_node n)
   at PascalABCCompiler.SyntaxTree.WalkingVisitorNew.ProcessNode(syntax_tree_node Node)
   at PascalABCCompiler.Compiler.InternalParseText(String fileName, String text, List`1 errorList, List`1 warnings, List`1 definesList)
   at PascalABCCompiler.Compiler.ConstructSyntaxTree(String unitFileName, CompilationUnit currentUnit, String sourceText)
   at PascalABCCompiler.Compiler.InitializeNewUnit(unit_or_namespace currentUnitNode, String UnitFileName, String UnitId, CompilationUnit& currentUnit, Dictionary`2& docs)
   at PascalABCCompiler.Compiler.CompileUnit(unit_node_list unitsFromUsesSection, Dictionary`2 directUnitsFromUsesSection, unit_or_namespace currentUnitNode, String previousPath)
   at PascalABCCompiler.Compiler.Compile()'
```

**Comment by SunSerega** [comment]
Вроде исправлено в https://github.com/pascalabcnet/pascalabcnet/commit/4bfd9d4cb2db920c73c8be1b21efd97f46e73087, но может стоит ещё тест добавить - какую сейчас ошибку выдаёт?

**Comment by miks1965** [comment]
Нет, это abcstatistics. Оно просто ничего теперь не делает в этом случае
