### ISSUE TITLE
Компилятор падает, если добавить result-атрибут к функции с параметрами

### ISSUE THREAD

**Issue by samuraiGH** [pascalabcnet/pascalabcnet#3048]
```pas
type
  [System.AttributeUsage(System.AttributeTargets.ReturnValue)]
  TestAttribute = sealed class(System.Attribute)
    
  end;
  
  
//TODO #2036
function f0 := 0;


[result: Test]
function f1(par1: integer):= 0;

begin end.
```

```console
ImageFileMachine imageFileMachine)
   в System.Reflection.Emit.AssemblyBuilder.Save(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   в PascalABCCompiler.Compiler.Compile() System.Exception: System.BadImageFormatException: Индекс не найден. (Исключение из HRESULT: 0x80131124)
   в System.Reflection.Emit.ModuleBuilder.PreSavePEFile(RuntimeModule module, Int32 portableExecutableKind, Int32 imageFileMachine)
   в System.Reflection.Emit.ModuleBuilder.PreSave(String fileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в System.Reflection.Emit.AssemblyBuilder.SaveNoLock(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в System.Reflection.Emit.AssemblyBuilder.Save(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   в PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   в PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   в PascalABCCompiler.Compiler.Compile()'
```

Возможно что-то не докрутили при фиксе #2880

**Comment by SunSerega** [comment]
У вас текст ошибки обрезался.
```
() : Внутренняя ошибка компилятора в модуле [pabcnetc.exe] :'System.Exception: System.BadImageFormatException: Index not found. (Exception from HRESULT: 0x80131124)
   at System.Reflection.Emit.ModuleBuilder.PreSavePEFile(RuntimeModule module, Int32 portableExecutableKind, Int32 imageFileMachine)
   at System.Reflection.Emit.ModuleBuilder.PreSave(String fileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   at System.Reflection.Emit.AssemblyBuilder.SaveNoLock(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   at System.Reflection.Emit.AssemblyBuilder.Save(String assemblyFileName, PortableExecutableKinds portableExecutableKind, ImageFileMachine imageFileMachine)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   at PascalABCCompiler.Compiler.Compile()'
```
Можно в окне ошибок нажать ПКМ>>Копировать.
