### ISSUE TITLE
Internal compiler error in module [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by Nigel-Galloway** [pascalabcnet/pascalabcnet#3204]
I was attempting to translate my F# entry on https://rosettacode.org/wiki/Bifid_cipher to PascalABC.NET but had to settle for something different because the following code causes the compiler to crash:

function polybius(alphabet:string;n,g:integer):(Dictionary<char,(integer,integer)>,Dictionary<(integer,integer),char>);
begin
  var ng:=Cartesian(1..n,1..g);
  Result:=(Dict(Zip(alphabet,ng)),Dict(Zip(ng,alphabet)));
end;
function fN(e:Dictionary<char,(integer,integer)>;n:string):(sequence of integer,sequence of integer):=(n.Substring(1).Scan(e[n[1]],(n,g)->e[g])).UnZipTuple;
var fX:((sequence of integer,sequence of integer),Dictionary<(integer,integer),char>)->string:=(n,e)->(n[0]+n[1]).Batch(2).Aggregate('',(n,g)->n+e[(g[0],g[1])]);
function encrypt(e:(Dictionary<char,(integer,integer)>,Dictionary<(integer,integer),char>);text:string):string;
begin
  Result:=fX(fN(e[0],text),e[1]);
end;
function decrypt(e:(Dictionary<char,(integer,integer)>,Dictionary<(integer,integer),char>);text:string):string;
begin
  var fG:(sequence of (integer,integer),Dictionary<(integer,integer),char>)->string:=(n,e)->n.Aggregate('',(n,g)->n+e[(g[0],g[1])]);
  var t:=fN(e[0],text); var z:=t[0].Interleave(t[1]).SplitAt(t[0].count);
  Result:=fG(z[0].ZipTuple(z[1]),e[1]);
end;
begin
  var p:=polybius('abcdefghiklmnopqrstuvwxyz',5,5); var s,e:string;
  s:='fleeatonce'; e:=encrypt(p,s); println($'{s} -> {e} -> {decrypt(p,e)}');
  s:='attackatdawn'; e:=encrypt(p,s); println($'{s} -> {e} -> {decrypt(p,e)}');
  p:=polybius('bgwkzqpndsioaxefclumthyvr',5,5);
  e:=encrypt(p,s); println($'{s} -> {e} -> {decrypt(p,e)}');
  s:='fleeatonce'; e:=encrypt(p,s); println($'{s} -> {e} -> {decrypt(p,e)}');
  p:=polybius('abcdefghijklmnopqrstuvwxyz0123456789',6,6);
  s:='theinvasionwillstarton1january2025'; e:=encrypt(p,s); println($'{s} -> {e} -> {decrypt(p,e)}');
end.

The only difference between the above and the version I have submitted is that fG has been moved from encrypt to the top level and renamed fX. Perhaps related is that in the code Aggregate('',(n,g)->n+e[(g[0],g[1])])  in the ide if I hover over n or g it gives the following result: n->array of integer g->string, obviously something is backwards here. As an observation should functional elements like Aggregate('',(n,g)->n+e[(g[0],g[1])]) be Aggregate('(n,g)->n+e[(g[0],g[1])])('') so I can curry them?

The details of the crash are:

Internal compiler error in module [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICompiledConstructorCall value)
   at PascalABCCompiler.NETGenerator.ILConverter.AssignToNamespaceVariableNode(IExpressionNode to, IExpressionNode from)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IBasicFunctionCallNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.GenerateInitCode(IVAriableDefinitionNode var, ILGenerator ilg)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertGlobalVariable(ICommonNamespaceVariableNode var)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICompiledConstructorCall value)
   at PascalABCCompiler.NETGenerator.ILConverter.AssignToNamespaceVariableNode(IExpressionNode to, IExpressionNode from)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IBasicFunctionCallNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.GenerateInitCode(IVAriableDefinitionNode var, ILGenerator ilg)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertGlobalVariable(ICommonNamespaceVariableNode var)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   at PascalABCCompiler.Compiler.Compile()'

//Here you can add your comment

17/09/2024 22:02:54
PascalABCCompiler.Core v3.10.0.3537 (07/09/2024), debug version
Runtime version: 4.0.30319.42000
OS version: Microsoft Windows NT 10.0.17763.0
Processor count: 4
WorkingSet: 130504 kb
StatesList: 
BeginCompileFile rc Bifid.pas
BeginParsingFile rc Bifid.pas
EndParsingFile rc Bifid.pas
SyntaxTreeConversion Standard
SyntaxTreeConversion LambdaAny
ReadPCUFile PABCSystem.pcu
ReadDLL System.dll
ReadDLL mscorlib.dll
ReadDLL System.Core.dll
ReadDLL System.Numerics.dll
ReadPCUFile PABCExtensions.pcu
ReadPCUFile __RedirectIOMode.pcu
ReadDLL System.Windows.Forms.dll
CompileInterface rc Bifid.pas
EndCompileFile rc Bifid.pas
SemanticTreeConversion Optimizer
CodeGeneration rc Bifid.exe
CompilationFinished rc Bifid.pas
Ready

Error[0]: Internal compiler error in module [pabcnetc.exe] :'System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICompiledConstructorCall value)
   at PascalABCCompiler.NETGenerator.ILConverter.AssignToNamespaceVariableNode(IExpressionNode to, IExpressionNode from)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IBasicFunctionCallNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.GenerateInitCode(IVAriableDefinitionNode var, ILGenerator ilg)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertGlobalVariable(ICommonNamespaceVariableNode var)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   at PascalABCCompiler.Compiler.Compile() System.Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PascalABCCompiler.NETGenerator.ILConverter.visit(ICompiledConstructorCall value)
   at PascalABCCompiler.NETGenerator.ILConverter.AssignToNamespaceVariableNode(IExpressionNode to, IExpressionNode from)
   at PascalABCCompiler.NETGenerator.ILConverter.visit(IBasicFunctionCallNode value)
   at PascalABCCompiler.NETGenerator.ILConverter.GenerateInitCode(IVAriableDefinitionNode var, ILGenerator ilg)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertGlobalVariable(ICommonNamespaceVariableNode var)
   at PascalABCCompiler.NETGenerator.ILConverter.ConvertFromTree(IProgramNode p, String TargetFileName, String SourceFileName, CompilerOptions options, String[] ResourceFiles)
   at PascalABCCompiler.Compiler.GenerateILCode(program_node programNode, CompilerOptions compilerOptions, List`1 resourceFiles)
   at PascalABCCompiler.Compiler.Compile()'

**Comment by samuraiGH** [comment]
minimal repro

```pas
var
  v: procedure:= 
    ()-> 'aboba'.Select(x-> x);

begin end.
```

**Comment by SunSerega** [comment]
This also causes it:
```
var
  v: function: function: integer := () -> () -> 0;

begin
end.
```
So the problem is the global variable being assigned lambda, with another lambda in its body.

**Comment by miks1965** [comment]
```
var
  fX: ((sequence of integer, sequence of integer),Dictionary<(integer, integer), char>)-> string 
    := (n, e)-> (n[0] + n[1]).Batch(2).Aggregate('', (n, g)-> n + e[(g[0], g[1])]);

begin
end.
```

**Comment by ibond84** [comment]
This code remove lambda procedure `lambda2<>` from the namespace function list. Therefore null reference exception. 

```
// Грубо - удаление мусора при разборе лямбд. Происходит исключение - заголовок разбирается, тело остается пустым - и из-за этого была ошибка #1270.
                    while (context._cmn.functions.Count > 0 && context._cmn.functions[context._cmn.functions.Count-1].function_code == null && context._cmn.functions[context._cmn.functions.Count - 1].name.StartsWith("<>lambda") && !context._cmn.functions[context._cmn.functions.Count - 1].name.StartsWith("<>lambda_initializer"))
                    {
#if DEBUG
                        //System.IO.File.AppendAllText("aa.txt", context._cmn.functions[context._cmn.functions.Count - 1].name+"\n");
#endif
                        context._cmn.functions.remove_at(context._cmn.functions.Count - 1);

                    }
```

**Comment by ibond84** [comment]
lambda2 ist not garbage. the body is added later..

**Comment by ibond84** [comment]
```
context._cmn.functions[context._cmn.functions.Count - 1].function_code = new statements_list(null);
```

**Comment by ibond84** [comment]
lambda_nested.pas from #1270 works

**Comment by ibond84** [comment]
With both codes the same amount of functions...

![image](https://github.com/user-attachments/assets/b268df53-dfd5-469f-afe5-8e604bbffd4e)
